#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_FILE="${1:-$ROOT_DIR/.env.phase1.local}"

server_json="$(cd "$ROOT_DIR" && bun run csh:keys)"
client_json="$(cd "$ROOT_DIR" && bun run csh:keys)"

server_private_key="$(printf '%s' "$server_json" | jq -r '.privateKeyHex')"
server_public_key="$(printf '%s' "$server_json" | jq -r '.publicKeyHex')"
client_private_key="$(printf '%s' "$client_json" | jq -r '.privateKeyHex')"
client_public_key="$(printf '%s' "$client_json" | jq -r '.publicKeyHex')"

{
  printf '# Generated by scripts/bootstrap-env.sh on %s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  printf 'CVM_RELAYS=%q\n' 'ws://127.0.0.1:10552'
  printf 'GW_PRIVATE_KEY=%q\n' "$server_private_key"
  printf 'GW_SERVER_INFO_NAME=%q\n' 'csh-phase1-host'
  printf 'GW_SERVER_INFO_WEBSITE=%q\n' ''
  printf 'GW_SERVER_INFO_PICTURE=%q\n' ''
  printf 'GW_ALLOW_UNLISTED_CLIENTS=%q\n' '0'
  printf 'GW_ALLOWED_PUBLIC_KEYS=%q\n' "$client_public_key"
  printf 'GW_ENCRYPTION_MODE=%q\n' 'required'
  printf 'CVM_CLIENT_PRIVATE_KEY=%q\n' "$client_private_key"
  printf 'CVM_SERVER_PUBKEY=%q\n' "$server_public_key"
  printf 'CVM_PROXY_ENCRYPTION_MODE=%q\n' 'required'
  printf 'CVM_LOG_LEVEL=%q\n' 'error'
  printf 'CVM_RESPONSE_LOOKBACK_SECONDS=%q\n' '300'
  printf 'CVM_SMOKE_SESSION_ID=%q\n' 'phase1-smoke'
  printf 'CVM_LIFECYCLE_SESSION_ID=%q\n' 'phase1-lifecycle'
  printf 'CSH_BROWSER_HOST=%q\n' '127.0.0.1'
  printf 'CSH_BROWSER_PORT=%q\n' '4318'
  printf 'CSH_BROWSER_ALLOW_REMOTE=%q\n' '0'
  printf 'CSH_BROWSER_AUTH_USER=%q\n' ''
  printf 'CSH_BROWSER_AUTH_PASSWORD=%q\n' ''
  printf 'CSH_SESSION_IDLE_TTL_SECONDS=%q\n' '1800'
  printf 'CSH_CLOSED_SESSION_TTL_SECONDS=%q\n' '300'
} > "$OUTPUT_FILE"

echo "Wrote $OUTPUT_FILE"
echo "Allowed client pubkey: $client_public_key"
